# Codecov Configuration for My Python Project
# A short description of the project

# Security: Only read configuration from main branch
codecov:
  strict_yaml_branch: main
  require_ci_to_pass: yes
  max_report_age: 12h

# Coverage targets and thresholds
coverage:
  precision: 2
  round: down
  range: 70..95

  status:
    project:
      default:
        # Current baseline: ~60%, targeting 60%+
        target: 60%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        # New code should meet 60% target
        target: 60%
        threshold: 5%
        if_ci_failed: error

# Multi-flag tracking for test types
flags:
  unit:
    # Unit tests should have higher coverage
    carryforward: true
    paths:
      - src/my_python_project/

  integration:
    # Integration tests may have lower coverage
    carryforward: true
    paths:
      - src/my_python_project/

  # Python version flags (CI workflow uploads)
  python-3.10:
    carryforward: true
  python-3.11:
    carryforward: true
  python-3.12:
    carryforward: true
  python-3.13:
    carryforward: true
  python-3.14:
    carryforward: true

# Component-based coverage tracking
component_management:
  individual_components:
    # Core module
    - component_id: core
      name: Core Module
      paths:
        - src/my_python_project/**

# Paths to ignore from coverage
ignore:
  # Test directories
  - "tests/**"
  - "**/*_test.py"
  - "**/test_*.py"

  # Validation scripts (not production code)
  - "validation/**"

  # Python cache and compiled files
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/*.pyo"
  - "**/*.pyd"
  - "**/*.so"
  - "**/*.dll"
  - "**/*.dylib"

  # Virtual environments
  - ".env/**"
  - ".venv/**"
  - "env/**"
  - "venv/**"
  - "ENV/**"
  - "env.bak/**"
  - "venv.bak/**"

  # IDE and editor files
  - ".vscode/**"
  - ".idea/**"
  - "*.swp"
  - "*.swo"
  - "*~"
  - ".DS_Store"

  # Build and distribution
  - "dist/**"
  - "build/**"
  - "*.egg-info/**"
  - ".eggs/**"
  - "*.egg"
  - "wheels/**"

  # Documentation
  - "docs/**"
  - "*.md"
  - "*.rst"

  # Configuration files
  - "*.toml"
  - "*.cfg"
  - "*.ini"
  - "*.yaml"
  - "*.yml"

  # Security and secrets
  - ".secrets*"
  - ".age"
  - ".sops.*"
  - "*.key"
  - "*.pem"

  # Dependency files
  - "poetry.lock"
  - "requirements*.txt"
  - "Pipfile.lock"

  # Git and CI
  - ".git/**"
  - ".github/**"
  - ".gitignore"
  - ".gitattributes"

  # Logs and temporary files
  - "logs/**"
  - "*.log"
  - ".pytest_cache/**"
  - ".mypy_cache/**"
  - ".ruff_cache/**"
  - "htmlcov/**"
  - ".coverage*"
  - "coverage.xml"

  # Temporary cleanup directory
  - "tmp_cleanup/**"

# Pull request comment configuration
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: yes
  require_head: yes

github_checks:
  annotations: true
